//
// This file was first generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// Modified by: Kartikeya Puri
// Do not re-generate.

package com.mitchell.examples.claim;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.lang.reflect.Method;
import java.util.List;
import java.util.ArrayList;

/**
 * <p>Java class for MitchellClaimType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MitchellClaimType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimantFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimantLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.mitchell.com/examples/claim}StatusCode" minOccurs="0"/>
 *         &lt;element name="LossDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LossInfo" type="{http://www.mitchell.com/examples/claim}LossInfoType" minOccurs="0"/>
 *         &lt;element name="AssignedAdjusterID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Vehicles" type="{http://www.mitchell.com/examples/claim}VehicleListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MitchellClaimType", propOrder = {
    "claimNumber",
    "claimantFirstName",
    "claimantLastName",
    "status",
    "lossDate",
    "lossInfo",
    "assignedAdjusterID",
    "vehicles"
})
public class MitchellClaimType {

    @XmlElement(name = "ClaimNumber", required = true)
    protected String claimNumber;
    @XmlElement(name = "ClaimantFirstName")
    protected String claimantFirstName;
    @XmlElement(name = "ClaimantLastName")
    protected String claimantLastName;
    @XmlElement(name = "Status")
    @XmlSchemaType(name = "string")
    protected StatusCode status;
    @XmlElement(name = "LossDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lossDate;
    @XmlElement(name = "LossInfo")
    protected LossInfoType lossInfo;
    @XmlElement(name = "AssignedAdjusterID")
    protected Long assignedAdjusterID;
    @XmlElement(name = "Vehicles")
    protected VehicleListType vehicles;

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the claimantFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantFirstName() {
        return claimantFirstName;
    }

    /**
     * Sets the value of the claimantFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantFirstName(String value) {
        this.claimantFirstName = value;
    }

    /**
     * Gets the value of the claimantLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantLastName() {
        return claimantLastName;
    }

    /**
     * Sets the value of the claimantLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantLastName(String value) {
        this.claimantLastName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCode }
     *     
     */
    public StatusCode getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCode }
     *     
     */
    public void setStatus(StatusCode value) {
        this.status = value;
    }

    /**
     * Gets the value of the lossDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLossDate() {
        return lossDate;
    }

    /**
     * Sets the value of the lossDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLossDate(XMLGregorianCalendar value) {
        this.lossDate = value;
    }

    /**
     * Gets the value of the lossInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LossInfoType }
     *     
     */
    public LossInfoType getLossInfo() {
        return lossInfo;
    }

    /**
     * Sets the value of the lossInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LossInfoType }
     *     
     */
    public void setLossInfo(LossInfoType value) throws Exception{
        nestedUpdateHelper(this.lossInfo, value);
    }

    /**
     * Gets the value of the assignedAdjusterID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAssignedAdjusterID() {
        return assignedAdjusterID;
    }

    /**
     * Sets the value of the assignedAdjusterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAssignedAdjusterID(Long value) {
        this.assignedAdjusterID = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleListType }
     *     
     */
    public VehicleListType getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleListType }
     *     
     */
    public void setVehicles(VehicleListType value) throws Exception {
        // In case of updates to the list of vehicles
        List<VehicleInfoType> newList = value.getVehicleDetails();
        List<VehicleInfoType> origList = this.vehicles.getVehicleDetails();
        List<VehicleInfoType> toAppend = new ArrayList<VehicleInfoType>();

        for(VehicleInfoType changed: newList)
        {
            String vin = changed.getVin();
            for(VehicleInfoType orig: origList)
            {
                //if the vehicle in the new list was present before, update non-null properties
                if (orig.getVin().equals(vin))
                {
                    nestedUpdateHelper(orig, changed);
                }

                // if this is a new vehicle, add to the list
                else
                    toAppend.add(changed);
            }  
        }
        origList.addAll(toAppend);
    }

    /*
     * Update properties of nested object orig with non-null properties of value.
     */
    private void nestedUpdateHelper(Object orig, Object value) throws Exception
    {
        Method[] listMethods = value.getClass().getMethods();

        //loop through all getters
        for (Method fn: listMethods)
        {
            String methodName = fn.getName();
            if(methodName.startsWith("get"))
            {
                Object returnedValue = fn.invoke(value);
                // if a value was updated, it will be non-null
                if (returnedValue != null && methodName != "getClass")
                {
                    //set the original property to the updated value
                    String setterName = methodName.replaceFirst("get", "set");
                    Method setter = orig.getClass().getMethod(setterName, fn.getReturnType());
                    setter.invoke(orig, returnedValue);
                }
            }
        }

    }
}
